# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(max_length=255, upload_to='images/logo/')),
                ('favicon_icon', models.ImageField(max_length=255, upload_to='images/favicon/')),
            ],
        ),
    ]
