# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=500)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icon.Icon')),
            ],
        ),
    ]
