# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('github_link', models.CharField(blank=True, max_length=255, null=True)),
                ('download_link', models.CharField(blank=True, max_length=255, null=True)),
                ('bitbucket_link', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('gems', models.ManyToManyField(blank=True, to='project.Gem')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='icon.Icon'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='tools',
            field=models.ManyToManyField(blank=True, to='project.Tool'),
        ),
    ]
