# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0001_initial'),
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='icon.Icon'),
        ),
    ]
