# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=1500, verbose_name='About')),
                ('cv_link', models.CharField(max_length=300)),
            ],
        ),
    ]
